//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakprjsonins.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int fotoId { get; set; }
        public string fotolar { get; set; }
        public int fotoEmlakId { get; set; }
        public int fotoUyeId { get; set; }
    
        public virtual Emlak Emlak { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
